name: Deploy Cloud Function

on:
  push:
    branches:
      
main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
    -  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_KEY }}
    steps:
    
name: Checkout repository
    uses: actions/checkout@v2

    
name: Install gcloud CLI
    uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
      version: 'latest'

    
name: Deploy function
    run: |
      gcloud functions deploy TDD-deploy2 \--gen2 \--runtime=nodejs20 \--region=us-east1 \--source=. \--entry-point=helloGET \--trigger-http \--allow-unauthentica