name: Deploy Cloud Functions
run-name: 🚀 ${{ github.actor }} is deploying all cloud functions
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: YOUR_PROJECT_ID
  SERVICE: YOUR_SERVICE_NAME
  REGION: YOUR_SERVICE_REGION

jobs:
  JMeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./HTTP_Request_Defaults.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
      - name: Analyze Results with Latency Lingo
        uses: latency-lingo/github-action@v0.0.2
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: result.jtl
          label: Checkout Flow Automated Test Plan
          format: jmeter
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_DEPLOY_KEY }}"

      - name: Run Unit Test
        run: cd ./functions/hotelGet/ && npm i && npm run test

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"

      - name: Use gcloud CLI
        run: gcloud info

      - name: Deploy to gen2 cloud function
        run: |
          gcloud functions deploy TDD-deploy2 \
            --gen2 \
            --runtime=nodejs20 \
            --region=us-east1 \
            --source=./functions/hotelGet/ \
            --entry-point=hotelGET \
            --trigger-http \
            --allow-unauthenticated
